### ISSUE TITLE
Installation fails on EKS on AWS

### ISSUE THREAD

**Issue by sarangid** [ListnPlay/charts#1]
The error is 
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

**Comment by jacobhjkim** [comment]
You need to have Prometheus operator installed.

**Comment by rjanovski** [comment]
in helm values set monitoring.enabled: false if you don't have prometheus.
