### ISSUE TITLE
failed when serviceMonitor is true

### ISSUE THREAD

**Issue by 1984man** [ListnPlay/charts#3]
Hello, I am new to helm. I met problem when I open monitoring.enable,  but it's ok when monitoring.enable == false
pls give me a help

yuliu@yuliu helm % helm install  druid --namespace "bi" myhelm/druid -f druid/values.yaml --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/yuliu/Library/Caches/helm/repository/druid-0.3.12.tgz

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
helm.go:81: [debug] unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:258
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by rjanovski** [comment]
in helm values set monitoring.enabled: false if you don't have prometheus.

**Comment by 1984man** [comment]
I want to set up monitoring for druid. I add prometheus with following steps 
https://github.com/prometheus-operator/kube-prometheus#Quickstart
and all the services in up now. but I could not get any points from druid in prometheus

another question:
![image](https://user-images.githubusercontent.com/12867863/118211570-e6815480-b49e-11eb-9b19-ba9a01bcd9b5.png)

1.how should I query the druid's metrics? 
2. am I miss some steps?


thanks again. I am lack of knowledge of helm and Prometheus.

**Comment by 1984man** [comment]
endpoints:
  - port: metrics
    interval: 30s

and is this metrics  should be a real port number?

**Comment by rjanovski** [comment]
did you try to add the [druid dashboard](https://github.com/ListnPlay/charts/blob/master/druid/druid-grafana-dashboard.json) to Grafana?

Please look for specific tutorials on prometheus and grafana on the Internet. Sorry, but I am unable to provide such support here.

**Comment by rjanovski** [comment]
did you try to add the [druid dashboard](https://github.com/ListnPlay/charts/blob/master/druid/druid-grafana-dashboard.json) to Grafana?


<img src="https://github.com/ListnPlay/charts/raw/master/druid/druid-grafana.png">

Please lookup tutorials on Grafana and Prometheus on the Internet. 
Sorry, but I can not provide such support here.
